Repository leonardoliragama/devops-aula07-, pull requests merged in 2018-09, with the labels that each got.

#3 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#5 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#7 Create jogovelha.py
  src/jogovelha.py
Labels: programação

#10 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#13 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#16 Integrar implementação v1.0
  src/jogovelha.py
Labels: programação

#18 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#20 Integrar requisitos v1.1
  docs/requisitos.md
Labels: análise

#23 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: arquitetura

#24 Gerar release v1.1
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações
